=== NexerG/Project-Aurora/Periodic/Data/XML/Schemas/AssetRegistryTypeSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraAssetRegistryTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraAssetRegistryTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:element name="IParseableTypes" type="types:IParseableTypes" />
  <xs:complexType name="IParseableTypes">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="AVulkanMesh" type="types:AVulkanMesh" />
  <xs:complexType name="AVulkanMesh">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="AssetEntry" type="types:AssetEntry" />
  <xs:complexType name="AssetEntry">
    <xs:sequence />
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="KeyType" type="allTypes:Uncategorized" />
    <xs:attribute name="ValueType" type="allTypes:Uncategorized" />
  </xs:complexType>
  <xs:element name="AssetRegistries" type="types:AssetRegistries" />
  <xs:complexType name="AssetRegistries">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Dictionary" type="types:AssetEntry">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="FontAsset" type="types:FontAsset" />
  <xs:complexType name="FontAsset">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="TextureAsset" type="types:TextureAsset" />
  <xs:complexType name="TextureAsset">
    <xs:sequence />
  </xs:complexType>
  <xs:element name="ControlStyle" type="types:ControlStyle" />
  <xs:complexType name="ControlStyle">
    <xs:sequence />
  </xs:complexType>
</xs:schema>

=== NexerG/Project-Aurora/ParticleSimulator/Data/XML/Documents/Registry.xml
<AssetRegistries xmlns="http://arctisaurora/AuroraAssetRegistryTypes"
				 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
				 xsi:schemaLocation="http://arctisaurora/AuroraAssetRegistryTypes ../Schemas/AssetRegistryTypeSchema.xsd" >
	<Dictionary Name="IDMap" KeyType="xs:unsignedInt" ValueType="Type"/>
	<Dictionary Name="meshes" KeyType="xs:string" ValueType="AVulkanMesh"/>
	<Dictionary Name="fonts" KeyType="xs:string" ValueType="FontAsset"/>
	<Dictionary Name="textures" KeyType="xs:string" ValueType="TextureAsset"/>
	<Dictionary Name="styles" KeyType="xs:string" ValueType="ControlStyle"/>
	<Dictionary Name="uiActions" KeyType="xs:string" ValueType="Action"/>
	<Dictionary Name="ActiveContexts" KeyType="xs:string" ValueType="Object"/>
	<Dictionary Name="Samplers" KeyType="xs:string" ValueType="SamplerAsset"/>

</AssetRegistries>
