=== NexerG/Project-Aurora/Periodic/Data/XML/Schemas/BootstrapTypeSchema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:types="http://arctisaurora/AuroraBootstrapTypes" xmlns:actions="http://arctisaurora/ActionDependencies" xmlns:allTypes="http://arctisaurora/AuroraTypes" elementFormDefault="qualified" targetNamespace="http://arctisaurora/AuroraBootstrapTypes" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:import schemaLocation="actionSchema.xsd" namespace="http://arctisaurora/ActionDependencies" />
  <xs:import schemaLocation="AllTypesSchema.xsd" namespace="http://arctisaurora/AuroraTypes" />
  <xs:element name="Step" type="types:Step" />
  <xs:complexType name="Step">
    <xs:sequence />
    <xs:attribute name="Action" type="actions:Bootstrap" />
  </xs:complexType>
  <xs:element name="Phase" type="types:Phase" />
  <xs:complexType name="Phase">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Step" type="types:Step">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
  </xs:complexType>
  <xs:element name="BootstrapSequence" type="types:BootstrapSequence" />
  <xs:complexType name="BootstrapSequence">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="unbounded" name="Phase" type="types:Phase">
        <xs:annotation>
          <xs:documentation></xs:documentation>
        </xs:annotation>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== NexerG/Project-Aurora/Periodic/Data/XML/Documents/Bootstrap.xml
<BootstrapSequence xmlns="http://arctisaurora/AuroraBootstrapTypes"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://arctisaurora/AuroraBootstrapTypes ../Schemas/BootstrapTypeSchema.xsd">

	<Phase Name="Bootstrap">
		<!--pre-renderer-->
		<Step Action="InputHandler.LoadInputs"/>
		<Step Action="Engine.SystemSetup"/>
		<Step Action="Engine.InitWindowing"/>
		<Step Action="AssetRegistries.InstantiateRegistries"/>
		<Step Action="AssetRegistries.RegisterSerializableTypes"/>
		<!--pre-renderer-->
		
		<Step Action="Renderer.InitRenderer"/>
		<Step Action="Renderer.PreInitialize"/>
		<Step Action="Renderer.Initialize"/>
		
		<!--post-renderer-->
		<Step Action="Context.LoadContexts"/>
		<Step Action="AssetRegistries.PrepareDefaultAssets"/>
		<!--post-renderer-->
		
		<Step Action="Renderer.SetupObjects"/>
		<Step Action="Renderer.PrepareDescriptors"/>
		<Step Action="Renderer.SetupPipelines"/>
		<Step Action="Renderer.CreateSyncObjects"/>
	</Phase>
	
</BootstrapSequence>
